"use client";
import { useEffect, useState } from "react";
import { projects as seedProjects } from "../../lib/content";
type Project = typeof seedProjects[number] & { published?: boolean };
export default function AdminPage() { const [projects, setProjects] = useState<Project[]>([]); const [title, setTitle] = useState(""); const [category, setCategory] = useState("Photography"); const [image, setImage] = useState("");
  useEffect(() => { const saved = localStorage.getItem("avant-admin-projects"); setProjects(saved ? JSON.parse(saved) : seedProjects.map(p => ({ ...p, published: true }))); }, []);
  function persist(next: Project[]) { setProjects(next); localStorage.setItem("avant-admin-projects", JSON.stringify(next)); }
  function addProject(e: React.FormEvent) { e.preventDefault(); if (!title || !image) return; const slug = title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,""); persist([{ slug, title, category, label: category, year: "2026", location: "Harare, Zimbabwe", image, layout: "wide", published: false }, ...projects]); setTitle(""); setImage(""); }
  return <main className="admin-shell"><aside className="admin-sidebar"><a className="admin-logo" href="/">AVANT<span>ADMIN</span></a><p className="eyebrow">Content studio</p><nav><a className="active" href="/admin">Projects</a><a href="/admin">Services</a><a href="/admin">Enquiries</a><a href="/">View site ↗</a></nav><small>Local prototype<br />PostgreSQL + Auth.js ready</small></aside><section className="admin-main"><div className="admin-top"><div><p className="eyebrow">Avant Creative Group</p><h1>Content studio</h1></div><a className="button button-accent" href="/">View site <span>↗</span></a></div><div className="admin-stats"><div><span>Published projects</span><strong>{projects.filter(p => p.published).length}</strong></div><div><span>Drafts</span><strong>{projects.filter(p => !p.published).length}</strong></div><div><span>Services</span><strong>06</strong></div></div><div className="admin-grid"><section className="admin-panel"><div className="panel-head"><h2>Portfolio projects</h2><span>{projects.length} total</span></div>{projects.map(project => <div className="admin-project" key={project.slug}><img src={project.image} alt="" /><div><strong>{project.title}</strong><span>{project.label} · {project.year}</span></div><button onClick={() => persist(projects.map(p => p.slug === project.slug ? { ...p, published: !p.published } : p))}>{project.published ? "Published" : "Draft"}</button></div>)}</section><section className="admin-panel"><div className="panel-head"><h2>Add a project</h2></div><form className="admin-form" onSubmit={addProject}><label>Project title<input value={title} onChange={e => setTitle(e.target.value)} placeholder="e.g. Summer Campaign" /></label><label>Category<select value={category} onChange={e => setCategory(e.target.value)}><option>Photography</option><option>Videography</option><option>Events</option><option>Real Estate</option><option>Campaigns</option></select></label><label>Image URL<input value={image} onChange={e => setImage(e.target.value)} placeholder="https://..." /></label><button className="button button-accent" type="submit">Save draft <span>↗</span></button></form><p className="admin-note">This local prototype stores drafts in your browser. The production version will replace this storage with PostgreSQL and Auth.js credentials on Dokploy.</p></section></div></section></main>; }
