"use client";
import { useEffect, useState } from "react";
import { projects, services } from "../lib/content";
import { SiteFooter } from "../components/marketing";
function Header({ onMenu }: { onMenu: () => void }) { return <header className="site-header"><a className="wordmark" href="/">AVANT<span>©</span></a><nav><a href="/work">Work</a><details className="nav-services"><summary>Services</summary><div><a href="/services">Overview</a><a href="/photography">Photography</a><a href="/film">Film</a></div></details><a href="/about">About</a><a href="/clients">Clients</a></nav><a className="header-cta" href="/contact">Book a shoot <span>↗</span></a><button className="menu-button" onClick={onMenu} aria-label="Open menu"><i /><i /></button></header>; }
function ProjectCard({ project, index }: { project: typeof projects[number]; index: number }) { return <a className={`project-card ${project.layout}`} href={`/work/${project.slug}`}><img src={project.image} alt={project.title} loading={index > 2 ? "lazy" : "eager"} /><div className="project-overlay"><span>{project.label}</span><strong>{project.title}</strong><small>{project.year} · {project.location}</small></div><div className="project-index">0{index + 1}</div></a>; }
const heroSlides = [
  { eyebrow: "Photography & film · Zimbabwe / Worldwide", title: <>Stories<br /><em>worth seeing.</em></>, intro: "Photography & film for brands, people and places.", image: "/media/victoria-falls-dawn.png" },
  { eyebrow: "Destination stories · Hwange / Victoria Falls", title: <>Places<br /><em>worth remembering.</em></>, intro: "Visual stories shaped by place, people and perspective.", image: "/media/hwange-elephant.png" },
  { eyebrow: "Creative direction · Harare / Worldwide", title: <>Brands<br /><em>worth becoming.</em></>, intro: "Strategic visual content with a distinctly Zimbabwean point of view.", image: "/media/harare-jacaranda.png" }
];
function HeroSlider() { const [active, setActive] = useState(0); useEffect(() => { const timer = window.setInterval(() => setActive(current => (current + 1) % heroSlides.length), 6500); return () => window.clearInterval(timer); }, []); const slide = heroSlides[active]; return <section className="hero hero-premium"><div className="hero-image" style={{ backgroundImage: `linear-gradient(90deg,rgba(4,28,37,.84),rgba(4,28,37,.22)),url(${slide.image})` }} key={active} /><div className="hero-copy" key={`copy-${active}`}><p className="eyebrow">{slide.eyebrow}</p><h1>{slide.title}</h1><p className="hero-intro">{slide.intro}</p><div className="hero-actions"><a className="button button-light" href="#work">View our work <span>↗</span></a><a className="text-link" href="#contact">Book a shoot <span>↗</span></a></div></div><div className="hero-meta"><span>{String(active + 1).padStart(2, "0")} — {String(heroSlides.length).padStart(2, "0")}</span><div className="hero-controls"><span>Explore</span>{heroSlides.map((item, index) => <button key={item.eyebrow} className={active === index ? "active" : ""} onClick={() => setActive(index)} aria-label={`Show slide ${index + 1}`}><i /></button>)}</div></div></section>; }
export default function Home() { const [menuOpen, setMenuOpen] = useState(false); return <main>
  <Header onMenu={() => setMenuOpen(true)} />
  {menuOpen && <div className="mobile-menu"><button className="close-menu" onClick={() => setMenuOpen(false)} aria-label="Close menu">×</button><p className="eyebrow">Avant Creative Group · Harare</p><nav><a href="/work" onClick={() => setMenuOpen(false)}>Work</a><a href="/photography" onClick={() => setMenuOpen(false)}>Photography</a><a href="/film" onClick={() => setMenuOpen(false)}>Film</a><a href="/services" onClick={() => setMenuOpen(false)}>Services</a><a href="/about" onClick={() => setMenuOpen(false)}>About</a><a href="/clients" onClick={() => setMenuOpen(false)}>Clients</a><a href="/contact" onClick={() => setMenuOpen(false)}>Contact</a></nav><div className="menu-foot"><span>Instagram</span><span>Facebook</span><span>WhatsApp</span></div></div>}
  <HeroSlider />
  <section className="intro"><p className="eyebrow">01 / The work</p><div><h2>We make images<br /><span>that stay with you.</span></h2><p className="body-copy">Avant is a creative media company built around visual storytelling. From the first frame to the final cut, we create work with presence, purpose and a point of view.</p><a className="text-link dark" href="/work">Explore selected work <span>↗</span></a></div></section>
  <section className="work-section" id="work"><div className="section-head"><div><p className="eyebrow">02 / Selected work</p><h2>Featured work</h2></div><a className="text-link dark" href="/work">View all work <span>↗</span></a></div><div className="project-grid">{projects.slice(0, 4).map((p, i) => <ProjectCard key={p.slug} project={p} index={i} />)}</div></section>
  <section className="services-section" id="services"><div className="section-head light"><div><p className="eyebrow">03 / What we do</p><h2>Built for the<br /><em>big picture.</em></h2></div><p className="body-copy">A nimble creative team for the moments that matter — and the ones you haven't imagined yet.</p></div><div className="service-list">{services.map(s => <a className="service-row" href="#contact" key={s.number}><span className="service-number">{s.number}</span><h3>{s.title}</h3><p>{s.description}</p><span className="service-arrow">↗</span><img src={s.image} alt="" loading="lazy" /></a>)}</div></section>
  <section className="about-section" id="about"><div className="about-photo" /><div className="about-copy"><p className="eyebrow">04 / About Avant</p><h2>Made in<br /><em>Zimbabwe.</em></h2><p className="body-copy">Founded in August 2022, Avant Creative Group is a collective of photographers, videographers, designers and storytellers. We make visual stories that leave lasting impressions — for local and cross-border clients.</p><a className="text-link dark" href="#contact">More about Avant <span>↗</span></a></div></section>
  <SiteFooter />
</main>; }
