"use client";
import { useState } from "react";
import { projects, services } from "../lib/content";
function Header({ onMenu }: { onMenu: () => void }) { return <header className="site-header"><a className="wordmark" href="/">AVANT<span>©</span></a><nav><a href="#work">Work</a><a href="#services">Services</a><a href="#about">About</a><a href="#contact">Contact</a></nav><a className="header-cta" href="#contact">Book a shoot <span>↗</span></a><button className="menu-button" onClick={onMenu} aria-label="Open menu"><i /><i /></button></header>; }
function ProjectCard({ project, index }: { project: typeof projects[number]; index: number }) { return <a className={`project-card ${project.layout}`} href={`/work/${project.slug}`}><img src={project.image} alt={project.title} loading={index > 2 ? "lazy" : "eager"} /><div className="project-overlay"><span>{project.label}</span><strong>{project.title}</strong><small>{project.year} · {project.location}</small></div><div className="project-index">0{index + 1}</div></a>; }
export default function Home() { const [menuOpen, setMenuOpen] = useState(false); return <main>
  <Header onMenu={() => setMenuOpen(true)} />
  {menuOpen && <div className="mobile-menu"><button className="close-menu" onClick={() => setMenuOpen(false)} aria-label="Close menu">×</button><p className="eyebrow">Avant Creative Group · Harare</p><nav><a href="#work" onClick={() => setMenuOpen(false)}>Work</a><a href="#services" onClick={() => setMenuOpen(false)}>Services</a><a href="#about" onClick={() => setMenuOpen(false)}>About</a><a href="#contact" onClick={() => setMenuOpen(false)}>Contact</a></nav><div className="menu-foot"><span>Instagram</span><span>Facebook</span><span>WhatsApp</span></div></div>}
  <section className="hero"><div className="hero-image" /><div className="hero-copy"><p className="eyebrow">Photography & film · Zimbabwe / Worldwide</p><h1>Stories<br /><em>worth seeing.</em></h1><p className="hero-intro">Photography & film for brands, people and places.</p><div className="hero-actions"><a className="button button-light" href="#work">View our work <span>↗</span></a><a className="text-link" href="#contact">Book a shoot <span>↗</span></a></div></div><div className="hero-meta"><span>01 — 06</span><span>Scroll to explore ↓</span></div></section>
  <section className="intro"><p className="eyebrow">01 / The work</p><div><h2>We make images<br /><span>that stay with you.</span></h2><p className="body-copy">Avant is a creative media company built around visual storytelling. From the first frame to the final cut, we create work with presence, purpose and a point of view.</p><a className="text-link dark" href="/work">Explore selected work <span>↗</span></a></div></section>
  <section className="work-section" id="work"><div className="section-head"><div><p className="eyebrow">02 / Selected work</p><h2>Recent stories</h2></div><a className="text-link dark" href="/work">View all work <span>↗</span></a></div><div className="project-grid">{projects.map((p, i) => <ProjectCard key={p.slug} project={p} index={i} />)}</div></section>
  <section className="services-section" id="services"><div className="section-head light"><div><p className="eyebrow">03 / What we do</p><h2>Built for the<br /><em>big picture.</em></h2></div><p className="body-copy">A nimble creative team for the moments that matter — and the ones you haven't imagined yet.</p></div><div className="service-list">{services.map(s => <a className="service-row" href="#contact" key={s.number}><span className="service-number">{s.number}</span><h3>{s.title}</h3><p>{s.description}</p><span className="service-arrow">↗</span><img src={s.image} alt="" loading="lazy" /></a>)}</div></section>
  <section className="about-section" id="about"><div className="about-photo" /><div className="about-copy"><p className="eyebrow">04 / About Avant</p><h2>Made in<br /><em>Zimbabwe.</em></h2><p className="body-copy">Founded in August 2022, Avant Creative Group is a collective of photographers, videographers, designers and storytellers. We make visual stories that leave lasting impressions — for local and cross-border clients.</p><a className="text-link dark" href="#contact">More about Avant <span>↗</span></a></div></section>
  <footer id="contact"><div className="footer-top"><p className="eyebrow">05 / Start a conversation</p><h2>Have a story<br /><em>in mind?</em></h2><a className="button button-accent" href="mailto:hello@avantgroup.co.zw">hello@avantgroup.co.zw <span>↗</span></a></div><div className="footer-bottom"><a className="wordmark" href="/">AVANT<span>©</span></a><div><span>Harare, Zimbabwe</span><span>Available worldwide</span></div><div><span>Instagram</span><span>WhatsApp</span></div><span>© 2026 Avant Creative Group</span></div></footer>
</main>; }
