"use client";
import { useEffect, useState } from "react";
import { projects as seedProjects, services, type Project } from "../lib/content";
import { SiteFooter, SiteHeader } from "../components/marketing";
function ProjectCard({ project, index }: { project: Project; index: number }) { return <a className={`project-card ${project.layout}`} href={`/work/${project.slug}`}><img src={project.image} alt={`${project.title} project image`} loading={index > 1 ? "lazy" : "eager"} width="1200" height="900" /><div className="project-overlay"><span>{project.label}</span><strong>{project.title}</strong><small>{project.year} · {project.location}</small></div><div className="project-index" aria-hidden="true">0{index + 1}</div></a>; }
const heroSlides = [
  { eyebrow: "Photography & film · Zimbabwe / Worldwide", title: <>Stories<br /><em>worth seeing.</em></>, intro: "Photography & film for brands, people and places.", image: "/media/victoria-falls-dawn.webp" },
  { eyebrow: "Destination stories · Hwange / Victoria Falls", title: <>Places<br /><em>worth remembering.</em></>, intro: "Visual stories shaped by place, people and perspective.", image: "/media/hwange-elephant.webp" },
  { eyebrow: "Creative direction · Harare / Worldwide", title: <>Brands<br /><em>worth becoming.</em></>, intro: "Strategic visual content with a distinctly Zimbabwean point of view.", image: "/media/harare-jacaranda.webp" }
];
function HeroSlider() { const [active, setActive] = useState(0); const [paused, setPaused] = useState(false); useEffect(() => { if (paused || window.matchMedia("(prefers-reduced-motion: reduce)").matches) return; const timer = window.setInterval(() => setActive(current => (current + 1) % heroSlides.length), 6500); return () => window.clearInterval(timer); }, [paused]); const slide = heroSlides[active]; return <section className="hero hero-premium" aria-roledescription="carousel" aria-label="Featured stories"><img className="hero-image" src={slide.image} alt="" width="2400" height="1600" fetchPriority="high" key={active} /><div className="hero-scrim" /><div className="hero-copy" key={`copy-${active}`}><p className="eyebrow">{slide.eyebrow}</p><h1>{slide.title}</h1><p className="hero-intro">{slide.intro}</p><div className="hero-actions"><a className="button button-light" href="#work">View our work <span aria-hidden="true">→</span></a><a className="text-link" href="/contact">Book a shoot <span aria-hidden="true">→</span></a></div></div><div className="hero-meta"><span aria-live="polite">Slide {String(active + 1).padStart(2, "0")} of {String(heroSlides.length).padStart(2, "0")}</span><div className="hero-controls"><button className="hero-pause" onClick={() => setPaused(value => !value)} aria-label={paused ? "Play slideshow" : "Pause slideshow"}>{paused ? "Play" : "Pause"}</button>{heroSlides.map((item, index) => <button key={item.eyebrow} className={active === index ? "active" : ""} onClick={() => { setActive(index); setPaused(true); }} aria-label={`Show slide ${index + 1}`} aria-current={active === index ? "true" : undefined}><i /></button>)}</div></div></section>; }
export default function Home() { const [projects, setProjects] = useState<Project[]>(seedProjects); const [projectLoadError, setProjectLoadError] = useState(false); useEffect(() => { fetch("/api/projects").then(response => response.ok ? response.json() : Promise.reject()).then(value => { const data = value as { projects?: Project[] }; if (data.projects?.length) setProjects(data.projects); }).catch(() => setProjectLoadError(true)); }, []); return <main>
  <SiteHeader />
  <HeroSlider />
  <section className="intro"><p className="eyebrow">01 / The work</p><div><h2>We make images<br /><span>that stay with you.</span></h2><p className="body-copy">Avant is a creative media company built around visual storytelling. From the first frame to the final cut, we create work with presence, purpose and a point of view.</p><a className="text-link dark" href="/work">Explore selected work <span aria-hidden="true">→</span></a></div></section>
  <section className="work-section" id="work"><div className="section-head"><div><p className="eyebrow">02 / Selected work</p><h2>Featured work</h2></div><a className="text-link dark" href="/work">View all work <span aria-hidden="true">→</span></a></div>{projectLoadError ? <p className="project-load-note">Showing our featured work while the latest portfolio is unavailable.</p> : null}<div className="project-grid">{projects.slice(0, 4).map((p, i) => <ProjectCard key={p.slug} project={p} index={i} />)}</div></section>
  <section className="services-section" id="services"><div className="section-head light"><div><p className="eyebrow">03 / What we do</p><h2>Built for the<br /><em>big picture.</em></h2></div><p className="body-copy">A nimble creative team for the moments that matter, including the ones you have not imagined yet.</p></div><div className="service-list">{services.map(s => <a className="service-row" href="/contact" key={s.number}><span className="service-number">{s.number}</span><h3>{s.title}</h3><p>{s.description}</p><span className="service-arrow" aria-hidden="true">→</span></a>)}</div></section>
  <section className="about-section" id="about"><div className="about-photo" role="img" aria-label="Jacaranda-lined street in Harare" /><div className="about-copy"><p className="eyebrow">04 / About Avant</p><h2>Made in<br /><em>Zimbabwe.</em></h2><p className="body-copy">Founded in August 2022, Avant Creative Group is a collective of photographers, videographers, designers and storytellers. We make visual stories that leave lasting impressions for local and cross-border clients.</p><a className="text-link dark" href="/about">More about Avant <span aria-hidden="true">→</span></a></div></section>
  <SiteFooter />
</main>; }
