"use client";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { usePathname } from "next/navigation";
import { services } from "../lib/content";

export function SiteHeader() {
  const pathname = usePathname(); const [menuOpen, setMenuOpen] = useState(false); const closeButton = useRef<HTMLButtonElement>(null); const close = () => setMenuOpen(false); const active = (path: string) => pathname === path || pathname.startsWith(`${path}/`);
  useEffect(() => { if (!menuOpen) return; const previous = document.activeElement as HTMLElement | null; closeButton.current?.focus(); const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") close(); }; document.addEventListener("keydown", onKey); document.body.style.overflow = "hidden"; return () => { document.removeEventListener("keydown", onKey); document.body.style.overflow = ""; previous?.focus(); }; }, [menuOpen]);
  const link = (path: string, label: string, closeMenu?: () => void) => <a className={active(path) ? "is-active" : undefined} aria-current={active(path) ? "page" : undefined} href={path} onClick={closeMenu}>{label}</a>;
  return <><header className="site-header"><a className="wordmark" href="/" aria-label="Avant Creative Group home"><img src="/avant-logo-black-transparent.png" alt="" width="1191" height="508" /></a><nav aria-label="Primary navigation">{link("/work", "Work")}{link("/gallery", "Gallery")}<details className={`nav-services${active("/services") || active("/photography") || active("/film") ? " is-active" : ""}`}><summary>Services</summary><div>{link("/services", "Overview")}{link("/photography", "Photography")}{link("/film", "Film")}</div></details>{link("/about", "About")}{link("/clients", "Clients")}<a className={`admin-login-link${active("/login") ? " is-active" : ""}`} aria-current={active("/login") ? "page" : undefined} href="/login">Admin</a></nav><a className="header-cta" href="/contact">Book a shoot <span aria-hidden="true">→</span></a><button className="menu-button" onClick={() => setMenuOpen(true)} aria-expanded={menuOpen} aria-controls="mobile-navigation" aria-label="Open menu"><i /><i /></button></header>{menuOpen ? <div className="mobile-menu" id="mobile-navigation" role="dialog" aria-modal="true" aria-label="Site navigation"><button ref={closeButton} className="close-menu" onClick={close} aria-label="Close menu">×</button><p className="eyebrow">Avant Creative Group · Harare</p><nav>{link("/work", "Work", close)}{link("/gallery", "Gallery", close)}{link("/services", "Services", close)}{link("/photography", "Photography", close)}{link("/film", "Film", close)}{link("/about", "About", close)}{link("/clients", "Clients", close)}{link("/contact", "Contact", close)}<a className={`admin-login-link${active("/login") ? " is-active" : ""}`} aria-current={active("/login") ? "page" : undefined} href="/login" onClick={close}>Admin</a></nav><div className="menu-foot"><a href="https://www.instagram.com/avantcreativegroup/" target="_blank" rel="noreferrer">Instagram</a><a href="mailto:hello@avantgroup.co.zw">Email</a></div></div> : null}</>;
}

export function SiteFooter() {
  return <footer id="contact"><div className="footer-top"><div><p className="eyebrow">Avant Creative Group</p><h2>Have a story<br /><em>in mind?</em></h2></div><div className="footer-callout"><p>Photography and film for brands, people and places.</p><a className="button button-accent" href="/contact">Start a conversation <span aria-hidden="true">→</span></a></div></div><div className="footer-bottom"><div className="footer-brand"><a className="footer-logo" href="/" aria-label="Avant Creative Group home"><img src="/avant-logo-transparent.png" alt="Avant Creative Group" width="1191" height="508" /></a><p>Stories worth seeing.<br />Made in Zimbabwe, available worldwide.</p></div><nav className="footer-links" aria-label="Footer navigation"><span className="footer-label">Explore</span><a href="/work">Work</a><a href="/gallery">Gallery</a><a href="/services">Services</a><a href="/clients">Clients</a><a href="/about">About</a></nav><div className="footer-contact"><span className="footer-label">Connect</span><span>Harare, Zimbabwe</span><a href="mailto:hello@avantgroup.co.zw">hello@avantgroup.co.zw</a><a href="https://www.instagram.com/avantcreativegroup/" target="_blank" rel="noreferrer">Instagram <span aria-hidden="true">↗</span></a></div><a className="footer-cta" href="/contact"><span>Start a project</span><strong>Let’s make something<br />worth remembering.</strong><i aria-hidden="true">→</i></a><div className="footer-meta"><span>© 2026 Avant Creative Group</span><div><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div><a className="developer-tag" href="https://www.spiritusglobal.tech" target="_blank" rel="noreferrer">Developed by Spiritus Systems</a></div></div></footer>;
}

export function PageIntro({ eyebrow, title, children, image }: { eyebrow: string; title: ReactNode; children: ReactNode; image?: string }) {
  return <section className="page-intro" style={image ? { backgroundImage: `linear-gradient(90deg,rgba(0,40,56,.86),rgba(0,40,56,.34)),url(${image})` } : undefined}><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><div className="page-intro-copy">{children}</div></section>;
}

export function ServicesList() {
  return <div className="service-list">{services.map(service => <a className="service-row" href="/contact" key={service.number}><span className="service-number">{service.number}</span><h3>{service.title}</h3><p>{service.description}</p><span className="service-arrow" aria-hidden="true">→</span></a>)}</div>;
}
